name: GitHub Pages

on:
  push:
    branches:
      - new-theme  # 改为监听新分支的推送

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: blowfish_theme  # 关键修改：指定从新分支拉取代码
          submodules: recursive  # 改为recursive确保子模块完全加载
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.145.0"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.Personal_Blog }}
          external_repository: minghf85/minghf85.github.io
          publish_dir: ./public
          publish_branch: main
          cname: xxx.com